### ISSUE TITLE
用户反馈：正确处理 obsidian 图片上传

### ISSUE THREAD

**Issue by Otto-J** [Otto-J/Obsidian-sync-xlog#6]
目前有点儿问题

**Comment by whitewatercn** [comment]
期待优化可以识别上传这类名称的图片`Pasted image 20231010085854.png`🙏

<img width="337" alt="image" src="https://github.com/Otto-J/sync-to-xlog/assets/58654928/fde4270b-0a75-415c-b73f-41aac1edb85e">

**Comment by Otto-J** [comment]
> 期待优化可以识别上传这类名称的图片`Pasted image 20231010085854.png`🙏
> 
> <img alt="image" width="337" src="https://user-images.githubusercontent.com/58654928/277112080-fde4270b-0a75-415c-b73f-41aac1edb85e.png">

我好像搞定了，明天再测试几次，发一个新版本

**Comment by Otto-J** [comment]
Done. #8
Welcom feedback!

**Comment by whitewatercn** [comment]
> Done. #8 Welcom feedback!

完美解决！
